/* eslint-env node */
module.exports = {
  preset: 'jest-expo',
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|firebase|@firebase)',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  testMatch: ['**/__tests__/**/*.(ts|tsx|js)', '**/*.(test|spec).(ts|tsx|js)'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/__tests__/**',
    '!src/app/components/**',
    '!src/app/constants/**',
    '!src/app/analysis/components/**',
    '!src/app/diary/creation/components/**',
    '!src/app/diary/edit/diaryEdit.tsx',
    '!src/app/diary/edit/components/**',
    '!src/app/diary/list/components/**',
    '!src/app/diary/show/diaryShow.tsx',
    '!src/app/diary/show/components/**',
    '!src/app/mentalHealthCheck/components/**',
    '!src/app/mentalHealthCheck/creation/components/**',
    '!src/app/mentalHealthCheck/list/components/**',
    '!src/app/mentalHealthCheck/show/components/**',
    '!src/app/myPage/components/**',
    '!src/app/searchFriend/components/**',
    '!src/app/searchFriend/searchFriend.tsx',
    '!src/app/mentalHealthCheck/creation/mentalHealthCheckCreate.tsx',
    '!src/app/mentalHealthCheck/show/mentalHealthCheckShow.tsx',
    '!src/app/_layout.tsx',
    '!src/app/index.tsx',
    '!src/app/auth/**',
    '!src/app/\\(tabs\\)/**',
  ],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
};